export default{

    WELCOME: "WELCOME",
    SIGNIN: "SIGN IN",
    FORGOTPASSWORD: "FORGOT PASSWORD",
    CHANGEPASSWORD: "CHANGE PASSWORD",
    SIGNUP: "SIGN UP",
    PERMISSIONS: "PERMISSIONS",
    HOME: "HOME",
    DEVICETRACKING: "DEVICE TRACKING",
    AVRECORDING: "AV RECORDING",
    RINGINGLOUD: "RINGING LOUD",
    MENU: "MENU",
    PROFILE: "PROFILE",
    TABS: "TABS",
    SCREEN: "SCREEN",
    CAMERA: "CAMERA"
}